version: '3.8'

services:
  app:
    image: tamj/redis-cache-demo-app:latest
    container_name: redis-cache-demo-app
    build: .
    ports:
      - "8080:8080"
    restart: always
    healthcheck:
      disable: true
    depends_on:
      - redis
  redis:
    image: redis:latest
    container_name: redis-db
    ports:
      - 6379:6379
    restart: always
    healthcheck:
      disable: true